name: Build CMake Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch: [aarch64, armv7, x86_64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake make libpulse-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Configure build with CMake
        run: |
          mkdir -p build
          cd build
          case "${{ matrix.target_arch }}" in
            aarch64)
              cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
                -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
              ;;
            armv7)
              cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armv7 \
                -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
                -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++
              ;;
            x86_64)
              cmake ..
              ;;
          esac

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulse-vumeter-${{ matrix.target_arch }}
          path: pulse-vumeter
