name: Build CMake Project

on:
  push:
    tags:
      - 'v*'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch: [x86_64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and cross-compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y make libpulse-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            build-essential

      - name: Set target compiler
        run: |
          case "${{ matrix.target_arch }}" in
            aarch64)
              echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              echo "CXX=aarch64-linux-gnu-g++" >> $GITHUB_ENV
              ;;
            armv7)
              echo "CC=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
              echo "CXX=arm-linux-gnueabihf-g++" >> $GITHUB_ENV
              ;;
            x86_64)
              echo "CC=gcc" >> $GITHUB_ENV
              echo "CXX=g++" >> $GITHUB_ENV
              ;;
          esac

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulse-vumeter-${{ matrix.target_arch }}
          path: pulse-vumeter
  
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pulse-vumeter
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pulse-vumeter-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
